import React from 'react';

const images = [
    {id: 0, src: '/images/one.jpg'},
    {id: 1, src: '/images/two.jpg'},
    {id: 2, src: '/images/three.jpg'},
    {id: 3, src: '/images/four.jpg'},
    {id: 4, src: '/images/five.jpg'},
    {id: 5, src: '/images/six.jpg'},
    {id: 6, src: '/images/seven.jpg'},
    {id: 7, src: '/images/eight.jpg'},
    {id: 8, src: '/images/nine.jpg'},
    {id: 9, src: '/images/ten.jpg'},
    {id: 10, src: '/images/eleven.jpg'},
    {id: 11, src: '/images/twelve.jpg'},
    {id: 12, src: '/images/thirteen.jpg'},
    {id: 13, src: '/images/fourteen.jpg'},
    {id: 14, src: '/images/fifteen.jpg'},
    {id: 15, src: '/images/one.jpg'},
    {id: 16, src: '/images/two.jpg'},
    {id: 17, src: '/images/three.jpg'},
    {id: 18, src: '/images/four.jpg'},
    {id: 19, src: '/images/five.jpg'},
    {id: 20, src: '/images/six.jpg'},
    {id: 21, src: '/images/seven.jpg'},
    {id: 22, src: '/images/eight.jpg'},
    {id: 23, src: '/images/nine.jpg'},
    {id: 24, src: '/images/ten.jpg'},
    {id: 25, src: '/images/eleven.jpg'},
    {id: 26, src: '/images/twelve.jpg'},
    {id: 27, src: '/images/thirteen.jpg'},
    {id: 28, src: '/images/fourteen.jpg'},
    {id: 29, src: '/images/fifteen.jpg'},
    {id: 30, src: '/images/one.jpg'},
    {id: 31, src: '/images/two.jpg'},
    {id: 32, src: '/images/three.jpg'},
    {id: 33, src: '/images/four.jpg'},
    {id: 34, src: '/images/five.jpg'},
    {id: 35, src: '/images/six.jpg'},
    {id: 36, src: '/images/seven.jpg'},
    {id: 37, src: '/images/eight.jpg'},
    {id: 38, src: '/images/nine.jpg'},
    {id: 39, src: '/images/ten.jpg'},
    {id: 40, src: '/images/eleven.jpg'},
    {id: 41, src: '/images/twelve.jpg'},
    {id: 42, src: '/images/thirteen.jpg'},
    {id: 43, src: '/images/fourteen.jpg'},
    {id: 44, src: '/images/fifteen.jpg'},
    {id: 45, src: '/images/one.jpg'},
    {id: 46, src: '/images/two.jpg'},
    {id: 47, src: '/images/three.jpg'},
    {id: 48, src: '/images/four.jpg'},
    {id: 49, src: '/images/five.jpg'},
    {id: 50, src: '/images/six.jpg'},
    {id: 51, src: '/images/seven.jpg'},
    {id: 52, src: '/images/eight.jpg'},
    {id: 53, src: '/images/nine.jpg'},
    {id: 54, src: '/images/ten.jpg'},
    {id: 55, src: '/images/eleven.jpg'},
    {id: 56, src: '/images/twelve.jpg'},
    {id: 57, src: '/images/thirteen.jpg'},
    {id: 58, src: '/images/fourteen.jpg'},
    {id: 59, src: '/images/fifteen.jpg'},
]

function selectedImageLoader() {
    return images;
}

export default selectedImageLoader;